"""librarians.py — keep the two indexes honest about how far behind they are.

Two stores answer two different questions, and a retrieval system needs both:

    guidance   curated notes, rules, memos      -> "what is the rule here?"
    archive    raw session transcripts          -> "when did this last happen, and what occurred?"

The designer's framing, 2026-07-30, and it is better than the one it replaced: rule and precedent, a
lawyer's two shelves. His illustration was a washer. *"1/2 washer"* is the rule, and it loses an
argument standing in a field; *"the day you drove four and a half hours back for one"* is the
precedent, and it wins instantly. The two stores join on the timestamp, so the small dated record
becomes the index into the large undated one.

★★★ THE FAILURE MODE IS DRIFT, NOT COST. Both indexes are append-only and cheap to refresh. The
danger is that one falls behind and **nothing says so**. A three-day-stale archive index does not
error — it quietly stops returning recent precedent, which looks exactly like a period with no
precedent to find. **Absence and staleness are indistinguishable from the outside**, and only one of
them is a bug.

★★★★★ STALENESS IS MEASURED AGAINST THE SOURCE, NEVER AGAINST A STORED TIMESTAMP.
  An index that records when it last ran will happily report itself current while the world moves on
  underneath it. Asking the index how fresh it is, is the same mistake as reading back a write
  through the accessor that made it: the answer is generated by the thing under test. So:

      guidance staleness = newest SOURCE FILE mtime   vs  index build time
      archive  staleness = newest turn ON DISK        vs  newest turn INDEXED

  Both compare the index to the world. Neither asks the index about itself.

    python librarians.py                       status; exit 2 if either is stale
    python librarians.py --guidance-root DIR   point it at your own tree
    python librarians.py --selftest            prove the alarm can actually fire

⚠ CANNOT-TELL IS ITS OWN EXIT CODE (3), not a pass. A missing index and a fresh index must never
  produce the same output — that conflation is the defect the whole project exists to remove.
"""
import argparse
import glob
import json
import os
import sys
import time

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

# Tolerances. The archive grows every session, so a small lag is normal and alarming on it would
# train the reader to ignore the alarm — which is how a real alarm becomes decorative.
GUIDANCE_TOLERANCE_H = float(os.environ.get("LIBRARIAN_GUIDANCE_TOLERANCE_H", "1.0"))
ARCHIVE_TOLERANCE_H = float(os.environ.get("LIBRARIAN_ARCHIVE_TOLERANCE_H", "24.0"))

OK, STALE, UNKNOWN = "OK", "STALE", "CANNOT-TELL"


def _newest_mtime(root, patterns=(".md",)):
    """Newest source mtime under `root`, or None if the tree is absent or empty.

    ⚠ None here means CANNOT TELL and every caller must treat it that way. Returning 0 or
      time.time() would each be a confident lie in a different direction.
    """
    if not root or not os.path.isdir(root):
        return None
    newest = None
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for fn in filenames:
            if patterns and not fn.endswith(tuple(patterns)):
                continue
            try:
                m = os.path.getmtime(os.path.join(dirpath, fn))
            except OSError:
                continue
            if newest is None or m > newest:
                newest = m
    return newest


def guidance_status(root, index_path, now=None):
    """Compare the newest SOURCE file against when the index was built.

    Returns (state, hours_behind_or_None, plain_english).
    """
    now = now if now is not None else time.time()
    newest = _newest_mtime(root)
    if newest is None:
        return UNKNOWN, None, ("guidance: no readable source tree at %r — this is CANNOT-TELL, not "
                               "'nothing to index'." % root)
    if not index_path or not os.path.exists(index_path):
        return STALE, None, ("guidance: %d source file(s) exist and there is NO INDEX at %r. Every "
                             "lookup is currently answering from an empty shelf."
                             % (_count(root), index_path))
    try:
        built = os.path.getmtime(index_path)
    except OSError:
        return UNKNOWN, None, "guidance: index exists but its mtime is unreadable — cannot tell."
    behind = (newest - built) / 3600.0
    if behind > GUIDANCE_TOLERANCE_H:
        return STALE, behind, ("guidance: source is %.1fh newer than the index. Notes written since "
                               "the last build are invisible to every query." % behind)
    return OK, behind, "guidance: index is current with its sources (%.2fh)." % max(0.0, behind)


def archive_status(root, index_path, now=None):
    """Compare the newest turn ON DISK against the newest turn INDEXED.

    ★ Deliberately NOT a file-count check. Counts match while contents diverge, and a count is
      exactly the kind of cheap proxy that keeps passing after the thing it stands for has broken.
    """
    now = now if now is not None else time.time()
    on_disk = _newest_mtime(root, patterns=(".jsonl", ".json", ".md", ".txt"))
    if on_disk is None:
        return UNKNOWN, None, ("archive: no readable transcript tree at %r — CANNOT-TELL." % root)
    indexed = _newest_indexed(index_path)
    if indexed is None:
        return STALE, None, ("archive: transcripts exist and nothing is indexed (%r). Precedent "
                             "lookups will return empty and look like 'it never happened'."
                             % index_path)
    behind = (on_disk - indexed) / 3600.0
    if behind > ARCHIVE_TOLERANCE_H:
        return STALE, behind, ("archive: newest turn on disk is %.1fh ahead of the newest turn "
                               "indexed. Recent precedent is unreachable, and an empty result is "
                               "indistinguishable from no precedent." % behind)
    return OK, behind, "archive: index reaches the newest turn on disk (%.2fh behind)." % max(0.0, behind)


def _count(root):
    n = 0
    for _d, dirnames, filenames in os.walk(root or "."):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        n += sum(1 for f in filenames if f.endswith(".md"))
    return n


def _newest_indexed(index_path):
    """Newest timestamp the index claims to cover, read from the index CONTENT.

    ⚠ NOT the index file's own mtime. Rewriting an index without adding anything updates the mtime
      and would report progress that did not happen — a fresh-looking file over stale content.
    """
    if not index_path or not os.path.exists(index_path):
        return None
    newest = None
    try:
        with open(index_path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                for key in ("mtime", "ts", "t", "timestamp"):
                    v = row.get(key) if isinstance(row, dict) else None
                    if isinstance(v, (int, float)):
                        newest = v if newest is None else max(newest, v)
                        break
    except OSError:
        return None
    return newest


def report(guidance_root, guidance_index, archive_root, archive_index, now=None):
    lines, states = [], []
    for fn, root, idx in ((guidance_status, guidance_root, guidance_index),
                          (archive_status, archive_root, archive_index)):
        st, _behind, msg = fn(root, idx, now=now)
        states.append(st)
        lines.append("  %-11s %s" % (st, msg))
    if STALE in states:
        rc = 2
    elif UNKNOWN in states:
        rc = 3
    else:
        rc = 0
    return rc, lines


def selftest():
    """★ A POSITIVE CONTROL. The point of these checks is that they FIRE, so the test that matters
    is not 'does it pass when healthy' but 'does it fail when broken'. A staleness alarm that has
    never been observed to trip is indistinguishable from one that cannot."""
    import shutil
    import tempfile
    fails = []
    d = tempfile.mkdtemp(prefix="_lib_")
    try:
        g = os.path.join(d, "guidance"); os.makedirs(g)
        a = os.path.join(d, "archive"); os.makedirs(a)
        gi = os.path.join(d, "guidance_index.json")
        ai = os.path.join(d, "archive_index.jsonl")
        NOW = time.time()

        with open(os.path.join(g, "rule.md"), "w", encoding="utf-8") as fh:
            fh.write("# a rule\n")
        with open(os.path.join(a, "turns.jsonl"), "w", encoding="utf-8") as fh:
            fh.write('{"t": 1}\n')

        # (1) no index at all must be STALE, never OK and never silent
        if guidance_status(g, gi)[0] != STALE:
            fails.append("a missing guidance index must be STALE, not a pass")
        if archive_status(a, ai)[0] != STALE:
            fails.append("a missing archive index must be STALE, not a pass")

        # (2) ★ THE ALARM MUST FIRE: index built, then a source file written after it
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write("{}")
        os.utime(gi, (NOW - 10 * 3600, NOW - 10 * 3600))
        os.utime(os.path.join(g, "rule.md"), (NOW, NOW))
        st, behind, _m = guidance_status(g, gi, now=NOW)
        if st != STALE:
            fails.append("★ guidance alarm did NOT fire on a 10h-newer source — it cannot fire")
        elif behind is None or behind < 9:
            fails.append("guidance reported STALE but the lag is wrong: %r" % behind)

        # (3) and it must go quiet again once the index catches up — an always-red alarm is noise
        os.utime(gi, (NOW + 60, NOW + 60))
        if guidance_status(g, gi, now=NOW)[0] != OK:
            fails.append("guidance stayed STALE after the index caught up — permanently red")

        # (4) ⚠ THE MTIME TRAP: rewriting the archive index without new content must NOT read as
        #     progress. This is the whole thesis of the file.
        with open(ai, "w", encoding="utf-8") as fh:
            fh.write('{"mtime": %f}\n' % (NOW - 72 * 3600))
        os.utime(os.path.join(a, "turns.jsonl"), (NOW, NOW))
        st_before = archive_status(a, ai, now=NOW)[0]
        os.utime(ai, (NOW + 600, NOW + 600))          # touch the index, add nothing
        if archive_status(a, ai, now=NOW)[0] != st_before:
            fails.append("★★ touching the archive index changed its verdict — it is reading its own "
                         "mtime instead of its content")
        if st_before != STALE:
            fails.append("archive alarm did not fire on a 72h content gap")

        # (5) an absent tree is CANNOT-TELL, distinct from both OK and STALE
        if guidance_status(os.path.join(d, "nope"), gi)[0] != UNKNOWN:
            fails.append("a missing source tree must be CANNOT-TELL, not STALE and not OK")

        # (6) exit codes must separate the three states
        rc_unknown, _ = report(os.path.join(d, "nope"), gi, a, ai)
        if rc_unknown != 2:
            # STALE dominates CANNOT-TELL when both are present; assert the dominance explicitly
            fails.append("mixed STALE+CANNOT-TELL should report the actionable one (2), got %r"
                         % rc_unknown)
    finally:
        shutil.rmtree(d, ignore_errors=True)

    for f in fails:
        print("  [FAIL] %s" % f)
    if not fails:
        print("  [PASS] missing index is STALE, the alarm fires on a real lag and clears when fixed, "
              "touching an index changes nothing, an absent tree is CANNOT-TELL.")
    print("\n  librarians selftest:", "PASS" if not fails else "FAIL")
    print("== librarians COMPLETE (rc=%d) ==" % (0 if not fails else 2))
    return 0 if not fails else 2


def main(argv=None):
    ap = argparse.ArgumentParser(description="Report how far behind each index is.")
    ap.add_argument("--guidance-root", default=os.environ.get("LIBRARIAN_GUIDANCE_ROOT", "memory"))
    ap.add_argument("--guidance-index", default=os.environ.get("LIBRARIAN_GUIDANCE_INDEX",
                                                               ".guidance_index.json"))
    ap.add_argument("--archive-root", default=os.environ.get("LIBRARIAN_ARCHIVE_ROOT", "archive"))
    ap.add_argument("--archive-index", default=os.environ.get("LIBRARIAN_ARCHIVE_INDEX",
                                                              ".archive_index.jsonl"))
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        return selftest()
    rc, lines = report(a.guidance_root, a.guidance_index, a.archive_root, a.archive_index)
    print("librarians:")
    for l in lines:
        print(l)
    print("  -> exit %d (0 both current, 2 something is STALE, 3 CANNOT-TELL)" % rc)
    return rc


if __name__ == "__main__":
    sys.exit(main())
